theme = "vesper"

[editor]
scrolloff = 8
line-number = "relative"

[editor.file-picker]
hidden = false

[editor.cursor-shape]
insert = "bar"

[keys.normal]
"{" = ["goto_prev_paragraph"]
"}" = ["goto_next_paragraph"]
"$" = "goto_line_end"
G = "goto_file_end"
esc = ["collapse_selection", "keep_primary_selection"]

[keys.normal.space]
w = ":write"
